/******************************************************************************/
/*           Generated by IBExpert 2023.9.13.1 21/09/2023 15:01:13            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'C:\Firebird\Firebird-2.5.9.27139-0_x86\bin\fbclient.dll';

CREATE DATABASE 'c4dvendas'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/*                                 Generators                                 */
/******************************************************************************/

CREATE GENERATOR GEN_CIDADES_ID;
SET GENERATOR GEN_CIDADES_ID TO 5571;

CREATE GENERATOR GEN_PESSOAS_ID;
SET GENERATOR GEN_PESSOAS_ID TO 1;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE CIDADES (
    ID           INTEGER NOT NULL,
    NOME         VARCHAR(60),
    UF           CHAR(2),
    CODIGO_IBGE  INTEGER
);

CREATE TABLE PESSOAS (
    ID             INTEGER NOT NULL,
    NOME           VARCHAR(60),
    FANTASIA       VARCHAR(60),
    CLIENTE        CHAR(1),
    FORNECEDOR     CHAR(1),
    CEP            VARCHAR(10),
    ID_CIDADE      INTEGER NOT NULL,
    ENDERECO       VARCHAR(60),
    NUMERO         VARCHAR(20),
    BAIRRO         VARCHAR(40),
    COMPLEMENTO    VARCHAR(40),
    TELEFONE       VARCHAR(15),
    CELULAR        VARCHAR(15),
    EMAIL          VARCHAR(50),
    TIPO_JURIDICO  SMALLINT DEFAULT 1,
    CPF            VARCHAR(14),
    RG             VARCHAR(14),
    CNPJ           VARCHAR(18),
    IE             VARCHAR(14),
    ATIVO          CHAR(1) DEFAULT 'S',
    NASCIMENTO     DATE,
    DH_CADASTRO    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO PESSOAS (ID, NOME, FANTASIA, CLIENTE, FORNECEDOR, CEP, ID_CIDADE, ENDERECO, NUMERO, BAIRRO, COMPLEMENTO, TELEFONE, CELULAR, EMAIL, TIPO_JURIDICO, CPF, RG, CNPJ, IE, ATIVO, NASCIMENTO, DH_CADASTRO) VALUES (1, 'Nome 1', 'Apelido 1', 'S', 'S', '46430000', 1971, 'Rua Jonatas Serrano', '1971', 'Jardim Alvorada', 'Casa', '7777777777', '8888888888', 'email@gmail.com', 0, '31312306572', '0123456789', NULL, NULL, 'S', '1980-01-01', '2023-09-06 18:32:21');


COMMIT WORK;



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE CIDADES ADD CONSTRAINT PK_CIDADES PRIMARY KEY (ID);
ALTER TABLE PESSOAS ADD CONSTRAINT PK_PESSOAS PRIMARY KEY (ID);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE PESSOAS ADD CONSTRAINT FK_PESSOAS_IDCIDADE FOREIGN KEY (ID_CIDADE) REFERENCES CIDADES (ID);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: CIDADES_BI */
CREATE TRIGGER CIDADES_BI FOR CIDADES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_cidades_id,1);
end
^

/* Trigger: PESSOAS_BI */
CREATE TRIGGER PESSOAS_BI FOR PESSOAS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_pessoas_id,1);
end
^
SET TERM ; ^

